loaded=true
originalCategoryIconBase=org/netbeans/modules/autoupdate/services/resources/icon-standard.png
originalCategoryName=STANDARD
originalDisplayName=NetBeans Distribution
originalEnabled=true
originalTrusted=true
originalUrl=https://netbeans.apache.org/nb/updates/19/updates.xml.gz?unique=NB_EXTIDE_PHP_WEBCOMMON08076a06e-9b10-4c88-b10f-411e210ff09c_b27ccead-4761-4332-95bb-6f514f8bba3a
